target:
- is_aki
continuous_cols:
- C-반응성 단백질 (CRP)
- 국제 정규화 비율 (INR)
- 나트륨
- 마그네슘
- 소변 비중
- 알부민
- 알칼리성 인산분해효소
- 염소
- 이온화 칼슘
- 인산
- 중탄산염
- 칼륨
- 칼슘 (총 칼슘)
- 포도당
- 프로트롬빈 시간
- 헤모글로빈
- 혈소판 수치
- 혈청크레아티닌_mean
- 혈청크레아티닌_std
- 활성화 부분 트롬보플라스틴 시간 (aPTT)
categorical_cols: []
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 14
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
task: classification
head: LinearHead
head_config: {}
embedding_dims: []
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.0005
loss: CrossEntropyLoss
metrics:
- accuracy
- f1_score
- auroc
metrics_prob_input:
- false
- false
- true
metrics_params:
- {}
- {}
- {}
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.ft_transformer
_model_name: FTTransformerModel
_backbone_name: FTTransformerBackbone
_config_name: FTTransformerConfig
input_embed_dim: 64
embedding_initialization: kaiming_uniform
embedding_bias: true
share_embedding: false
share_embedding_strategy: fraction
shared_embedding_fraction: 0.25
attn_feature_importance: true
num_heads: 8
num_attn_blocks: 8
transformer_head_dim: null
attn_dropout: 0.1
add_norm_dropout: 0.1
ff_dropout: 0.1
ff_hidden_multiplier: 4
transformer_activation: GEGLU
batch_size: 512
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 100
min_epochs: 1
max_time: null
accelerator: gpu
devices: 1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 25
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: true
track_grad_norm: -1
progress_bar: rich
precision: 32
trainer_kwargs: {}
project_name: AKInator_Project
run_name: AKI2024
exp_watch: null
log_target: tensorboard
log_logits: false
exp_log_freq: 100
optimizer: AdamW
optimizer_params:
  weight_decay: 1.0e-05
lr_scheduler: ReduceLROnPlateau
lr_scheduler_params:
  mode: min
  factor: 0.05
  patience: 5
  threshold: 0.0001
lr_scheduler_monitor_metric: valid_loss
categorical_dim: 0
enable_checkpointing: true
